version: "3.7"

services:
  backend-files:
    image: postmodern.alexdaniel.org/ttuwiki-backend-files:latest
    build:
      context: .
    volumes:
      - /home/ttuwiki/data/ttuwikifiles/data:/srv/data
      - /home/ttuwiki/data/ttuwikifiles/logs:/srv/logs
    networks:
      - caddy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first

      labels:
        caddy: files.ttuwiki.org, www.files.ttuwiki.org, files.ttuwiki.ee, www.files.ttuwiki.ee
        caddy.tls: alex.jakimenko+caddy@gmail.com
        caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
